# Generated by Django 5.0.7 on 2024-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=23)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=24)),
                ('place_type', models.CharField(max_length=15)),
            ],
        ),
    ]
