# Generated by Django 5.0.7 on 2024-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='lot_number_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='map',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='map',
            name='place_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='map',
            name='place_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='map',
            name='road_name_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='place_type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
