# Generated by Django 5.0.7 on 2024-07-22 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodoStore',
            fields=[
                ('podo_store_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, verbose_name='상품 이름')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
            ],
        ),
        migrations.CreateModel(
            name='PodoUsageHistory',
            fields=[
                ('podo_usage_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='구매일')),
                ('podo_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PodoUsageHistories', to='podos.podostore')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PodoUsageHistories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
