# Generated by Django 5.0.7 on 2024-07-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PodoPointList",
            fields=[
                (
                    "podo_point_list_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "item_name",
                    models.CharField(max_length=100, verbose_name="적립 포인트 항목 이름"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="포인트")),
            ],
        ),
        migrations.CreateModel(
            name="PodoHistory",
            fields=[
                (
                    "podo_history_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="구매일")),
                ("remaining_points", models.IntegerField(verbose_name="당시 남은 포인트")),
                (
                    "podo_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PodoHistories",
                        to="podos.podostore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PodoHistories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "podo_point_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PodoHistories",
                        to="podos.podopointlist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PodoUsageHistory",
        ),
    ]
