# Generated by Django 5.0.7 on 2024-08-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podos', '0002_podopointlist_podohistory_delete_podousagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podohistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='구매일'),
        ),
    ]
