# Generated by Django 5.0.7 on 2024-07-22 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetBloodSugar',
            fields=[
                ('target_blood_sugar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(default=0, verbose_name='키')),
                ('weight', models.IntegerField(default=0, verbose_name='몸무게')),
                ('target_blood_sugar', models.IntegerField(default=0, verbose_name='목표 혈당 수치')),
            ],
        ),
        migrations.CreateModel(
            name='BloodSugarState',
            fields=[
                ('blood_sugar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('morning_fasting_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='아침 공복 혈당')),
                ('noon_fasting_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='점심 공복 혈당')),
                ('evening_fasting_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='저녁 공복 혈당')),
                ('morning_post_meal_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='아침 식후 2시간 이후 혈당')),
                ('noon_post_meal_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='점심 식후 2시간 이후 혈당')),
                ('evening_post_meal_blood_sugar', models.IntegerField(blank=True, null=True, verbose_name='저녁 식후 2시간 이후 혈당')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BloodSugarStates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
