# Generated by Django 5.0.7 on 2024-07-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodsugars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetbloodsugar',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='targetbloodsugar',
            name='max_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='targetbloodsugar',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
    ]
