# Generated by Django 5.0.7 on 2024-07-26 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diets", "0002_dietset_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="diet_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diets",
                to="diets.dietset",
            ),
        ),
    ]
